# Generated by Django 3.1.5 on 2021-01-13 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('endereço', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.editora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.genero')),
            ],
        ),
    ]
