# Generated by Django 3.1.5 on 2021-01-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_editora_livro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editora',
            options={'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name_plural': 'Livros'},
        ),
        migrations.AddField(
            model_name='livro',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='preço',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
        ),
    ]
