# Generated by Django 3.1.5 on 2021-01-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20210113_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
