# Generated by Django 3.1.5 on 2021-01-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('endereço', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Editoras',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('descrição', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=9)),
                ('image', models.FileField(blank=True, null=True, upload_to='products/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='products/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='products/')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.editora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.genero')),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
