# Generated by Django 3.1.5 on 2021-02-05 18:50

from django.db import migrations, models
import loja.models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, validators=[loja.models.validate_interval_age]),
        ),
    ]
