# Generated by Django 3.1.5 on 2021-02-06 16:28

from django.db import migrations, models
import loja.models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20210205_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=10, validators=[loja.models.validate_interval_age]),
            preserve_default=False,
        ),
    ]
