# Generated by Django 3.1.5 on 2021-01-25 12:54

from django.db import migrations, models
import loja.models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20210121_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[loja.models.validate_interval]),
        ),
    ]
