# Generated by Django 3.1.5 on 2021-02-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='loja.Livro'),
        ),
    ]
