# Generated by Django 3.1.5 on 2021-02-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_auto_20210209_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
