# Generated by Django 3.1.7 on 2021-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_compra_metodo_de_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AddField(
            model_name='compra',
            name='estado_da_compra',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue')], max_length=10, null=True),
        ),
    ]
