# Generated by Django 3.1.7 on 2021-02-23 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_auto_20210223_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='timestamp2',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
