# Generated by Django 3.1.5 on 2021-02-24 01:32

from django.db import migrations, models
import loja.models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_compra_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='nota',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1, validators=[loja.models.validate_interval_nota]),
        ),
        migrations.AddField(
            model_name='livro',
            name='numero_de_avaliacoes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
