# Generated by Django 3.1.5 on 2021-02-24 03:08

from django.db import migrations, models
import loja.models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_auto_20210223_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='nota',
            field=models.FloatField(default=0.0, validators=[loja.models.validate_interval_nota]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='numero_de_avaliacoes',
            field=models.FloatField(default=0),
        ),
    ]
