# Generated by Django 3.1.5 on 2021-02-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0020_auto_20210224_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='avaliado',
            field=models.BooleanField(default=False),
        ),
    ]
