# Generated by Django 3.1.5 on 2021-02-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0022_auto_20210224_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='metodo_de_pagamento',
            field=models.CharField(choices=[('Boleto', 'Boleto'), ('Cartão', 'Cartão')], max_length=10),
        ),
    ]
